CREATE TABLE IF NOT EXISTS `performance_metrics` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`metric` TEXT NOT NULL,
	`value` REAL NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `detection_history` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`label` TEXT NOT NULL,
	`accuracy` REAL NOT NULL,
	`count` INTEGER NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `dataset` (
	`label` TEXT NOT NULL PRIMARY KEY,
	`count` INTEGER NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `recorded_streams` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`stream` INTEGER NOT NULL,
	`path` TEXT,
	`started_at` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`ended_at` TEXT,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);